### ISSUE TITLE
New Kick chat not working

### ISSUE THREAD

**Issue by Adtrix** [steveseguin/social_stream#317]
Hi.
Thanks for all the awesome updates so far.
It seems that the new chat under the KICKs new website/GUI does not communicate with Social Stream in any direction. Specifically when using chat side panel on main channel page but also when using that same chat in popout mode (one with refreshed look). The creator dashboard still seem to have the old v1 KICK GUI, v1 chat included which works as normal. The new v2 chat however does seem to have working 7TV (not v1 anymore), hence why it would be ideal to support the new version. Would be great to have the new chat working without breaking compatibility with the currently working old v1 chat. I'm using the 3.4.4 version of the chrome extension.

To reproduce:

Working: https://kick.com/username/chatroom
Not working: https://kick.com/popout/username/chat

Where "username" is the Kick channel of your choice

Thank you in advance,
Best regards 😊

**Comment by steveseguin** [comment]
Thank you.  I'll look into it.

**Comment by steveseguin** [comment]
It seems to be working currently, but seems that when I enable the 7TV extension, it breaks things.

![image](https://github.com/user-attachments/assets/e0f161b5-29e7-457e-a29a-54191c4bd126)
https://kick.com/popout/classybeef/chat

I'll try to address this all, somehow. thank you

**Comment by steveseguin** [comment]
I pushed a fix.  Download an try please

**Comment by Adtrix** [comment]
Thank you for your quick response.

I've re-installed 3.4.6 and uninstalled 7TV for testing. It seems that the problem persists despite 7TV being uninstalled. While I can send messages from the new Kick chat popup window ( https://kick.com/popout/username/chat ) and Social Stream will receive messages sent from there, reversely sending messages from the menu bar in Social Stream dockable chat (as an OBS Panel) to the new Kick popup chat still does not work (new Kick chat popup does not receive messages from overlay). Old Kick chat popup ( https://kick.com/username/chatroom ) still does receive messages from SS dockable chat. I've observed that both Twitch chat popup and Kick chat popup (old version) while receiving messages from Social Stream highlight their text boxes and the messages from SS dockable chat arrive. For the new Kick chat popup this does not seem to be the case. It's textbox is never highlighted as if SS would not recognize where it is. That would be my guess.

Hopefully it makes sense 😂

Best Regards

**Comment by steveseguin** [comment]
ah.  Well, my brain isn't working 100% these days, but if the issue is that you can't send messages from the dock to kick, I've pushed an update just now that tries to fix it.  It seems to work for me, but you'll need to test and confirm that for me

**Comment by Adtrix** [comment]
Hi again.
After testing 3.4.10 extenstion, there seems to be another problem occuring when using SS for a longer period. When I send messages from the dockable overaly they go trough as expected and show up at both dedicated chats....but only the messages from KICK do not show up in the dockable streaming chat. If I send word "Test" in the overlay to all, that message would arrive to both chats, but only the Twitch message would appear in the overlay (not the one from Kick). As the problem happens, reversely sending messages from the Kick chat popup does not make it appear in the overlay.
Keep in mind that this behaviour occurs randomly and is specific to the new KICK chat popup window ( https://kick.com/popout/username/chat ). Furthermore, when sending a /clear command in the overlay to all, the KICK popup seem to receive it, but the command is never executed (I sometimes like to clear both chats with one global /clear from the overlay.
It might seem like everything works a first when testing, only after a while and some messages later things will start to break.

To help find the cause of the problem I'll add some extra info:
+ I use Thorium 128.0.6613.189 as my browser
+ I do launch each chat in a separate independent window (as web apps)
+ The problem is gone when using the old Kick chat popup instead of the new one
+ I put the chat popup windows on a second monitor either behind the OBS window or minimize them.

**Comment by D2theR** [comment]
If it helps helps anyone coming here from the Google when using the stand alone app.

I had to:
- Switch to the Beta version. 
- Add a "Other chat sites" option using: https://kick.com/popout/{username}/chat
- Pick a different/newer User Agent from the gear menu (Chrome 144 - Linux)

I assume this is due to them adding/requiring a pin verification code on login and it fails standard auth.
